
version: '3.8'

services:
  # Serviço principal do Bitcoin DCA Pro
  app:
    container_name: bitcoin-dca-pro
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      # Adicione outras variáveis de ambiente necessárias aqui
    networks:
      - app-network
      
  # Alternativa usando Nginx como proxy reverso
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - nginx_logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  nginx_logs:
