
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wccbdayxpucptynpxhew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjY2JkYXl4cHVjcHR5bnB4aGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTk0NTcsImV4cCI6MjA1OTk3NTQ1N30.077c9Tq7DpKiMZmpI6ARnI5KwGj8Q0h0viE3FenC0t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',  // Necessário para OAuth com servidores externos
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,  // Permite que o Supabase detecte automaticamente códigos na URL
    storage: localStorage,
  }
});
